// Package builderbundle builds the single script the topology builder page
// loads in place of the grapheditor's many source files.
//
// mxGraph's development loader (src/js/mxClient.js) writes a <script> tag for
// each of its 140 source files, and the builder page loads 16 other
// grapheditor scripts. Each is a round trip, which on a remote phenix server
// adds seconds to every visit even when cached. The bundle is the same code in
// the same order, in one file. The server builds it from the served grapheditor
// files, so it cannot drift from them.
package builderbundle

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"regexp"
)

// scripts are the builder page's scripts, in page order. mxClient.js is
// expanded in place with the files it would include.
var scripts = []string{ //nolint:gochecknoglobals // fixed list
	"js/Init.js",
	"deflate/pako.min.js",
	"deflate/base64.js",
	"jscolor/jscolor.js",
	"sanitizer/sanitizer.min.js",
	mxClient,
	"js/EditorUi.js",
	"js/Editor.js",
	"js/Sidebar.js",
	"js/Graph.js",
	"js/Format.js",
	"js/Shapes.js",
	"js/Actions.js",
	"js/Menus.js",
	"js/Toolbar.js",
	"js/Dialogs.js",
	"utils/js/jsoneditor.js",
}

const mxClient = "src/js/mxClient.js"

var (
	// The block of mxClient.include calls that loads mxGraph's sources.
	includeBlock = regexp.MustCompile(
		`(?s)// PREPROCESSOR-REMOVE-START\n(?://[^\n]*\n)*if \(mxForceIncludes[^\n]*\n\{\n// PREPROCESSOR-REMOVE-END\n(.*?)// PREPROCESSOR-REMOVE-START\n\}\n// PREPROCESSOR-REMOVE-END\n`,
	)
	include = regexp.MustCompile(
		`mxClient\.include\(mxClient\.basePath\+'/([^']+)'\);`,
	)
)

// Build returns the bundle for the grapheditor directory in dir.
func Build(dir fs.FS) ([]byte, error) {
	var out bytes.Buffer

	out.WriteString("// Generated by phenix/web/builderbundle; do not edit.\n")

	for _, name := range scripts {
		src, err := fs.ReadFile(dir, name)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", name, err)
		}

		if name != mxClient {
			appendScript(&out, name, src)

			continue
		}

		block := includeBlock.FindSubmatchIndex(src)
		if block == nil {
			return nil, errors.New("mxClient.js: include block not found")
		}

		// mxClient.js without its loader, then what the loader would load
		appendScript(&out, name, append(bytes.Clone(src[:block[0]]), src[block[1]:]...))

		includes := include.FindAllSubmatch(src[block[2]:block[3]], -1)
		if len(includes) == 0 {
			return nil, errors.New("mxClient.js: no includes found")
		}

		for _, inc := range includes {
			path := "src/" + string(inc[1])

			incSrc, err := fs.ReadFile(dir, path)
			if err != nil {
				return nil, fmt.Errorf("reading %s: %w", path, err)
			}

			appendScript(&out, path, incSrc)
		}
	}

	return out.Bytes(), nil
}

// appendScript adds a script, ending it so the next cannot continue its last
// statement.
func appendScript(out *bytes.Buffer, name string, src []byte) {
	fmt.Fprintf(out, "\n// --- %s\n", name)
	out.Write(src)
	out.WriteString("\n;\n")
}
