package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	v1 "phenix/types/version/v1"
	v2 "phenix/types/version/v2"
)

const (
	schemaDraft202012 = "https://json-schema.org/draft/2020-12/schema"
	repoRawPrefix     = "https://raw.githubusercontent.com/sandialabs/sceptre-phenix/main/schemas"
)

type openAPIDoc struct {
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	var (
		outDir          string
		versionsCSV     string
		failOnNoSchemas bool
	)

	flag.StringVar(&outDir, "out", "../../schemas", "directory where JSON schema files will be written")
	flag.StringVar(&versionsCSV, "versions", "v1,v2", "comma-separated OpenAPI versions to export")
	flag.BoolVar(&failOnNoSchemas, "fail-on-no-schemas", true, "fail when an expected OpenAPI version has no schemas")
	flag.Parse()

	openAPIByVersion := map[string][]byte{
		"v1": v1.OpenAPI,
		"v2": v2.OpenAPI,
	}

	versions := strings.Split(versionsCSV, ",")
	for i := range versions {
		versions[i] = strings.TrimSpace(versions[i])
	}

	for _, version := range versions {
		openAPI, ok := openAPIByVersion[version]
		if !ok {
			exitf("unknown version %q; supported versions are: v1, v2", version)
		}

		doc, err := parseOpenAPIDoc(openAPI)
		if err != nil {
			exitf("parse %s OpenAPI: %v", version, err)
		}

		if len(doc.Components.Schemas) == 0 {
			if failOnNoSchemas {
				exitf("%s OpenAPI has no components.schemas section", version)
			}
			continue
		}

		if err := exportVersionSchemas(outDir, version, doc.Components.Schemas); err != nil {
			exitf("export %s schemas: %v", version, err)
		}
	}
}

func parseOpenAPIDoc(raw []byte) (*openAPIDoc, error) {
	var doc openAPIDoc

	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, err
	}

	return &doc, nil
}

func exportVersionSchemas(outDir, version string, schemas map[string]any) error {
	versionDir := filepath.Join(outDir, version)
	if err := os.MkdirAll(versionDir, 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", versionDir, err)
	}

	kinds := make([]string, 0, len(schemas))
	for kind := range schemas {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)

	rewritten := rewriteForJSONSchema(clone(schemas))
	defs, ok := rewritten.(map[string]any)
	if !ok {
		return fmt.Errorf("rewrite schemas failed: unexpected type %T", rewritten)
	}

	for _, kind := range kinds {
		fileName := strings.ToLower(kind) + ".schema.json"
		filePath := filepath.Join(versionDir, fileName)

		autoGenDesc := fmt.Sprintf(
			"Autogenerated from phenix embedded OpenAPI %s component schema %s.",
			strings.ToUpper(version), kind,
		)

		doc := map[string]any{
			"$schema":     schemaDraft202012,
			"$id":         fmt.Sprintf("%s/%s/%s", repoRawPrefix, version, fileName),
			"title":       fmt.Sprintf("phenix %s %s", kind, strings.ToUpper(version)),
			"description": autoGenDesc,
			"$ref":        fmt.Sprintf("#/$defs/%s", kind),
			"$defs":       defs,
		}

		formatted, err := json.MarshalIndent(doc, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal schema for %s %s: %w", version, kind, err)
		}

		formatted = append(formatted, '\n')
		if err := os.WriteFile(filePath, formatted, 0o644); err != nil {
			return fmt.Errorf("write schema file %s: %w", filePath, err)
		}
	}

	return nil
}

func clone(v any) any {
	switch t := v.(type) {
	case map[string]any:
		out := make(map[string]any, len(t))
		for k, child := range t {
			out[k] = clone(child)
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, child := range t {
			out[i] = clone(child)
		}
		return out
	default:
		return t
	}
}

func rewriteForJSONSchema(v any) any {
	switch t := v.(type) {
	case map[string]any:
		for k, child := range t {
			t[k] = rewriteForJSONSchema(child)
		}

		if ref, ok := t["$ref"].(string); ok && strings.HasPrefix(ref, "#/components/schemas/") {
			t["$ref"] = strings.Replace(ref, "#/components/schemas/", "#/$defs/", 1)
		}

		nullable, _ := t["nullable"].(bool)
		if nullable {
			if typ, ok := t["type"]; ok {
				t["type"] = addNullType(typ)
			}
			delete(t, "nullable")
		}

		return t
	case []any:
		for i, child := range t {
			t[i] = rewriteForJSONSchema(child)
		}
		return t
	default:
		return t
	}
}

func addNullType(rawType any) any {
	switch t := rawType.(type) {
	case string:
		if t == "null" {
			return t
		}
		return []any{t, "null"}
	case []any:
		for _, item := range t {
			if s, ok := item.(string); ok && s == "null" {
				return t
			}
		}
		return append(t, "null")
	default:
		return rawType
	}
}

func exitf(format string, a ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "error: "+format+"\n", a...)
	os.Exit(1)
}
