package builder

import (
	"encoding/hex"
	"fmt"
	"net"
	"net/netip"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/mitchellh/mapstructure"

	"phenix/store"
	"phenix/types"
	v1 "phenix/types/version/v1"
)

// TopologyAPIVersion is the config apiVersion of topologies generated by this
// package.
const TopologyAPIVersion = "phenix.sandia.gov/v1"

// DefaultTopologyName is the topology name [TopologyName] proposes for a
// document whose name leaves none, as its export files are named "topology".
const DefaultTopologyName = "topology"

// topologyNameInvalid matches the runs of characters a config name may not
// hold (see phenix/api/config.NameRegex).
var topologyNameInvalid = regexp.MustCompile(`[^A-Za-z0-9_@.-]+`)

// TopologyName is the name proposed for the topology of a document named
// name, in the Builder's Publish dialog (configName in
// src/js/src/builder/publish.js) and wherever a document is published
// without one: each run of characters a config name may not hold becomes one
// hyphen, and hyphens at either end are dropped.
func TopologyName(name string) string {
	proposed := strings.Trim(topologyNameInvalid.ReplaceAllString(name, "-"), "-")
	if proposed == "" {
		return DefaultTopologyName
	}

	return proposed
}

// Topology is the authoritative projection of a builder document onto phenix
// configuration data.
type Topology struct {
	// Spec is the topology spec in the stored representation, ready to be used
	// as store.Config.Spec.
	Spec map[string]any
	// VLANAliases maps network names to their integer VLAN alias, ready to be
	// used as an experiment's spec.vlans.aliases.
	VLANAliases map[string]int
	// Warnings collects non-fatal issues found while mapping the document,
	// each with its code and the device it is about.
	Warnings []Issue
}

// TopologyExport is the topology config a document publishes as (see
// [Document.ExportTopologyConfig]).
type TopologyExport struct {
	// Config is the topology config publishing stores.
	Config *store.Config
	// VLANAliases maps network names to their integer VLAN alias (see
	// [Topology.VLANAliases]). A topology config holds none.
	VLANAliases map[string]int
	// Warnings collects non-fatal issues found while mapping the document.
	Warnings []Issue
	// PublishBlockers are why publishing refuses Config although phenix's
	// config validation accepts it, one error per check in the order
	// publishing makes them (see [Document.PublishTopologyConfig]), or none.
	// Each lists its problems as issues (see [ErrorIssues]).
	PublishBlockers []error
}

// InterfaceVLANError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a projection in which interfaces have no VLAN (see
// [checkInterfaceVLANs]), and is one of the [TopologyExport.PublishBlockers]
// of such a projection.
type InterfaceVLANError struct {
	// Problems names each device and interface, and what to do about it.
	Problems []string

	// issues holds the issue of each problem, in the same order.
	issues []Issue
}

func (e *InterfaceVLANError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// Issues returns one issue of code [CodeInterfaceVLANMissing] for each
// problem, saying what the problem says, at the interface it names.
func (e *InterfaceVLANError) Issues() []Issue {
	return problemIssues(CodeInterfaceVLANMissing, e.Problems, e.issues)
}

// InterfaceAddressError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a document in which interfaces on one network use the same IP or MAC
// address (see [Document.checkInterfaceAddresses]), and is one of the
// [TopologyExport.PublishBlockers] of such a document.
type InterfaceAddressError struct {
	// Problems names each address, its network and the interfaces that use
	// it.
	Problems []string

	// issues holds the issue of each problem, in the same order.
	issues []Issue
}

func (e *InterfaceAddressError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// Issues returns one issue for each problem, of code [CodeInterfaceIPShared]
// or [CodeInterfaceMACShared], saying what the problem says, at the first
// interface of a device that is not included that uses the address.
func (e *InterfaceAddressError) Issues() []Issue {
	return problemIssues(CodeInterfaceIPShared, e.Problems, e.issues)
}

// NodeHostnameError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a projection with hostnames phenix refuses (see [checkHostnames]), and
// is one of the [TopologyExport.PublishBlockers] of such a projection.
type NodeHostnameError struct {
	// Problems names each hostname and why phenix refuses it.
	Problems []string

	// issues holds the issue of each problem, in the same order.
	issues []Issue
}

func (e *NodeHostnameError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// Issues returns one issue for each problem, of the code of why phenix
// refuses the hostname (such as [CodeNodeHostnameReserved]), saying what the
// problem says, at the device's hostname.
func (e *NodeHostnameError) Issues() []Issue {
	return problemIssues(CodeNodeHostnameShort, e.Problems, e.issues)
}

// problemIssues returns the issues of a publish blocker: located, when it
// holds one for each problem, or else an issue of code for each problem,
// located nowhere, as a blocker made outside this package has.
func problemIssues(code Code, problems []string, located []Issue) []Issue {
	if len(located) == len(problems) {
		return slices.Clone(located)
	}

	issues := make([]Issue, len(problems))

	for i, problem := range problems {
		issues[i] = NewIssue(code, "", problem)
	}

	return issues
}

// specNode is the document node a node of the projection's topology spec was
// made from: its index among the document's nodes, and its ID.
type specNode struct {
	index int
	id    string
}

// projectedNodes returns the document node each node of the spec
// [Document.ToTopology] makes comes from, in the spec's order: every device
// that is not included from another topology.
func (d *Document) projectedNodes() []specNode {
	var nodes []specNode

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if !projectedDevice(node) {
			continue
		}

		nodes = append(nodes, specNode{index: i, id: node.ID})
	}

	return nodes
}

// projectedDevice reports whether the node is one [Document.ToTopology]
// writes to the topology spec: a device that is not included from another
// topology.
func projectedDevice(node *Node) bool {
	return node.Kind == NodeKindDevice && node.Device != nil && node.Device.IncludedFrom == ""
}

// locate gives an issue about the spec node at index the path below the
// document node it was made from (nodes[3].<below>) and that node's ID. An
// index past the nodes leaves the issue where it is.
func locate(issue Issue, nodes []specNode, index int, below string) Issue {
	if index < 0 || index >= len(nodes) {
		return issue
	}

	issue.Path = fmt.Sprintf("nodes[%d].%s", nodes[index].index, below)
	issue.NodeID = nodes[index].id

	return issue
}

// ToTopology maps a builder document onto a phenix topology spec and the
// experiment VLAN alias map.
//
// Mapping rules:
//
//   - switch, note, and group nodes are omitted; they carry no phenix
//     semantics,
//   - devices from included topologies ([Device.IncludedFrom]) are omitted,
//     and the document's includeTopologies are written instead, so phenix
//     merges those devices back in and a publish never duplicates them,
//   - each other device contributes its complete node spec verbatim, including
//     general.description and any keys unknown to this package,
//   - an interface whose handle is connected to a network has its VLAN set to
//     that network's canonical name,
//   - interfaces that are not connected are preserved unchanged (including any
//     VLAN they already declare, or none, which [Document.PublishTopologyConfig]
//     refuses),
//   - every network carrying an integer alias contributes a VLAN alias.
//
// The document is validated first; an invalid document is never mapped.
func (d *Document) ToTopology() (*Topology, error) {
	if err := d.Validate(); err != nil {
		return nil, err
	}

	handleNetworks := d.handleNetworks()

	var (
		nodes    = make([]any, 0, len(d.Nodes))
		warnings []Issue
	)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if !projectedDevice(node) {
			continue
		}

		spec, nodeWarnings, err := deviceSpec(node, i, handleNetworks)
		if err != nil {
			return nil, fmt.Errorf("mapping device %q: %w", node.Device.Hostname, err)
		}

		warnings = append(warnings, nodeWarnings...)
		nodes = append(nodes, spec)
	}

	aliases := make(map[string]int)

	for i := range d.Networks {
		network := &d.Networks[i]
		if network.Alias != nil {
			aliases[network.Name] = *network.Alias
		}
	}

	spec := map[string]any{keyNodes: nodes}
	if d.Source != nil && len(d.Source.IncludeTopologies) > 0 {
		spec["includeTopologies"] = slices.Clone(d.Source.IncludeTopologies)
	}

	return &Topology{
		Spec:        spec,
		VLANAliases: aliases,
		Warnings:    warnings,
	}, nil
}

// ToTopologyConfig maps the document onto a stored Topology config named name.
func (d *Document) ToTopologyConfig(name string) (*store.Config, []Issue, error) {
	topology, err := d.ToTopology()
	if err != nil {
		return nil, nil, err
	}

	config, err := topologyConfig(name, topology)
	if err != nil {
		return nil, nil, err
	}

	return config, topology.Warnings, nil
}

// topologyConfig is the Topology config named name holding the projection's
// spec (the same map, not a copy).
func topologyConfig(name string, topology *Topology) (*store.Config, error) {
	config, err := store.NewConfig("topology/" + name)
	if err != nil {
		return nil, fmt.Errorf("creating topology config: %w", err)
	}

	config.Version = TopologyAPIVersion
	config.Spec = topology.Spec

	return config, nil
}

// PublishTopologyConfig projects the document onto a topology config and runs
// the checks publishing makes, so a caller about to publish a topology can
// authoritatively verify complete node specs: every interface of a device
// phenix starts has a VLAN (see [checkInterfaceVLANs]), no two interfaces on
// one network use one IP or MAC address (see
// [Document.checkInterfaceAddresses]), phenix
// accepts every hostname (see [checkHostnames]), and the spec passes the
// existing phenix topology schema validation (types.ValidateConfigSpec, which
// does not resolve included topologies from the store).
//
// This is deliberately separate from [Document.Validate], which validates the
// draft working copy: a working copy may legitimately contain interfaces that
// are not yet connected to a network and have no VLAN, or that share an
// address, or a hostname imported from a topology older phenix stored, which
// a published topology may not.
//
// It is the entry point for callers that intend to store the result. What
// only publishing refuses (see [Document.projectTopology]) is reported first,
// whatever else phenix's config validation finds, as its errors name what to
// fix: the first check that fails, so interfaces without a VLAN before
// addresses interfaces share, and those before hostnames phenix refuses.
func (d *Document) PublishTopologyConfig(name string) (*store.Config, []Issue, error) {
	config, _, warnings, err := d.PublishTopology(name)

	return config, warnings, err
}

// PublishTopology is [Document.PublishTopologyConfig] that also returns the
// projection the config holds, for a publisher that needs more of it (its
// VLAN aliases, say) without projecting the document again. The config's
// spec is the projection's, so neither may be changed while the other is
// in use.
func (d *Document) PublishTopology(name string) (*store.Config, *Topology, []Issue, error) {
	projection, err := d.projectTopology(name)
	if err != nil {
		return nil, nil, nil, err
	}

	if len(projection.blockers) > 0 {
		return nil, nil, projection.warnings, projection.blockers[0]
	}

	if projection.schema != nil {
		return nil, nil, projection.warnings, projection.schema
	}

	return projection.config, projection.topology, projection.warnings, nil
}

// ExportTopologyConfig projects the document onto a topology config and runs
// the checks of [Document.PublishTopologyConfig], for a caller that hands the
// config out rather than stores it. One that only publishing refuses, as an
// interface has a blank VLAN, interfaces share an address, or phenix would
// refuse a hostname when it creates an experiment, is returned with every
// such error, the one PublishTopologyConfig returns first, as its
// PublishBlockers.
//
// A projection that fails phenix's config validation is refused. When an
// interface's vlan key is missing or null, or a hostname is a single
// character, which the schema refuses too, the error is the one publishing
// makes of it, naming the interfaces or the hostnames. Otherwise it is the
// schema's own error: blank VLANs, shared addresses and the hostnames phenix
// refuses only when it creates an experiment, which the schema accepts, are
// not why the config cannot be exported.
func (d *Document) ExportTopologyConfig(name string) (*TopologyExport, error) {
	projection, err := d.projectTopology(name)
	if err != nil {
		return nil, err
	}

	if projection.schema != nil {
		switch {
		case projection.absentVLANs != nil:
			return nil, projection.absentVLANs
		case projection.shortHostnames != nil:
			return nil, projection.shortHostnames
		default:
			return nil, projection.schema
		}
	}

	return &TopologyExport{
		Config:          projection.config,
		VLANAliases:     projection.topology.VLANAliases,
		Warnings:        projection.warnings,
		PublishBlockers: projection.blockers,
	}, nil
}

// PublishBlockers returns every check only publishing makes that the
// document's projection onto the topology config named name fails, in the
// order publishing makes them (see [Document.projectTopology]), whether or
// not phenix's config validation accepts the projection. It is for a caller
// that names everything that blocks a publication:
// [Document.ExportTopologyConfig] returns alone a blocker the schema refuses
// too.
func (d *Document) PublishBlockers(name string) ([]error, error) {
	projection, err := d.projectTopology(name)
	if err != nil {
		return nil, err
	}

	return projection.blockers, nil
}

// topologyProjection is a document projected onto a topology config, with
// what the checks of publishing found.
type topologyProjection struct {
	config *store.Config
	// topology is the projection config was made from; config.Spec is its
	// Spec.
	topology *Topology
	warnings []Issue
	// blockers are the checks only publishing makes that config fails, in the
	// order publishing makes them (see [Document.projectTopology]).
	blockers []error
	// absentVLANs is the blocker naming the interfaces without a VLAN when
	// one of them has no vlan key, or a null one, which phenix's schema
	// refuses too, and nil otherwise.
	absentVLANs error
	// shortHostnames is the blocker naming the hostnames phenix refuses when
	// one of them is a single character, which phenix's schema refuses too,
	// and nil otherwise.
	shortHostnames error
	// schema is why phenix's config validation refuses config, or nil.
	schema error
}

// projectTopology projects the document onto a topology config named name
// and runs every check of publishing on it. It is the one place that decides
// what publishing refuses although phenix's config validation may accept it,
// which [Document.PublishTopologyConfig] refuses and
// [Document.ExportTopologyConfig] reports, in this order: interfaces without
// a VLAN (see [checkInterfaceVLANs]), then addresses interfaces share (see
// [Document.checkInterfaceAddresses]), then hostnames phenix refuses (see
// [checkHostnames]), whose warnings it adds to the projection's. Then it runs
// the phenix topology schema.
func (d *Document) projectTopology(name string) (*topologyProjection, error) {
	topology, err := d.ToTopology()
	if err != nil {
		return nil, err
	}

	config, err := topologyConfig(name, topology)
	if err != nil {
		return nil, err
	}

	projection := &topologyProjection{
		config: config, topology: topology, warnings: slices.Clone(topology.Warnings),
		blockers: nil, absentVLANs: nil, shortHostnames: nil, schema: nil,
	}

	nodes := d.projectedNodes()

	if vlans, absent := checkInterfaceVLANs(config.Spec, nodes); vlans != nil {
		blocker := fmt.Errorf("validating topology projection: %w", vlans)
		projection.blockers = append(projection.blockers, blocker)

		if absent {
			projection.absentVLANs = blocker
		}
	}

	if addresses := d.checkInterfaceAddresses(); addresses != nil {
		projection.blockers = append(projection.blockers, fmt.Errorf("validating topology projection: %w", addresses))
	}

	hostnames, short, hostnameWarnings := checkHostnames(config.Spec, nodes)
	projection.warnings = append(projection.warnings, hostnameWarnings...)

	if hostnames != nil {
		blocker := fmt.Errorf("validating topology projection: %w", hostnames)
		projection.blockers = append(projection.blockers, blocker)

		if short {
			projection.shortHostnames = blocker
		}
	}

	if err := types.ValidateConfigSpec(*config); err != nil {
		projection.schema = fmt.Errorf("validating topology projection: %w", err)
	}

	return projection, nil
}

// checkInterfaceVLANs refuses a topology spec in which an interface of a node
// phenix starts has no VLAN: none at all, or an empty one. The phenix topology
// schema requires only the vlan key, so phenix stores such a topology, but
// minimega refuses the interface when the experiment starts ("VLAN must be
// non-empty string"). A VLAN that names no network of the document is kept:
// phenix allocates VLANs by name. External nodes are not started, and need
// none. The error names each device and interface to fix: an interface by
// its position when it has no name, or shares it with another. It also
// reports whether one of those interfaces has no vlan key or a null one,
// which phenix's schema refuses as well, rather than a blank VLAN, which it
// accepts. nodes are the document nodes the spec's nodes were made from (see
// [Document.projectedNodes]), which locate the issue of each problem.
func checkInterfaceVLANs(spec map[string]any, nodes []specNode) (*InterfaceVLANError, bool) {
	entries, _ := spec[keyNodes].([]any)

	var (
		problems []string
		issues   []Issue
		absent   bool
	)

	for position, entry := range entries {
		node, ok := entry.(map[string]any)
		if !ok || node["external"] != nil {
			continue
		}

		hostname := specString(node, "general", "hostname")
		ifaces := specNodeInterfaces(node)
		labels := interfaceLabels(ifaces)

		for index, iface := range ifaces {
			named, missing := specInterfaceVLAN(iface)
			if named {
				continue
			}

			absent = absent || missing

			problem := fmt.Sprintf(
				"interface %s of device %q has no VLAN: connect it to a network, or type a VLAN for it",
				labels[index], hostname,
			)

			issue := NewIssue(CodeInterfaceVLANMissing, "", problem)
			issue.Field = fmt.Sprintf("spec.network.interfaces.%d.vlan", index)

			problems = append(problems, problem)
			issues = append(issues, locate(issue, nodes, position, fmt.Sprintf("device.spec.network.interfaces[%d]", index)))
		}
	}

	if len(problems) == 0 {
		return nil, false
	}

	return &InterfaceVLANError{Problems: problems, issues: issues}, absent
}

// checkHostnames refuses a topology spec with a hostname phenix refuses (see
// [checkHostname]). The error names each hostname and why, in phenix's words.
// It also reports whether one of them is a single character, and returns the
// warnings phenix logs then about the hostnames it accepts. External nodes are
// not started, and phenix checks none of their hostnames. nodes are the
// document nodes the spec's nodes were made from, which locate the issues.
func checkHostnames(spec map[string]any, nodes []specNode) (*NodeHostnameError, bool, []Issue) {
	var (
		problems         []string
		issues, warnings []Issue
		short            bool
	)

	startedNodes(spec, func(position int, hostname, osType string) {
		warning, err := checkHostname(hostname, osType)
		if err != nil {
			issue := NewIssue(hostnameCode(hostname, true), "", err.Error())
			issue.Field = specHostname

			problems = append(problems, err.Error())
			issues = append(issues, locate(issue, nodes, position, hostnamePath))
			short = short || isShortHostname(hostname)
		}

		if warning != "" {
			issue := NewIssue(hostnameCode(hostname, false), "", warning)
			issue.Field = specHostname

			warnings = append(warnings, locate(issue, nodes, position, hostnamePath))
		}
	})

	if len(problems) == 0 {
		return nil, false, warnings
	}

	return &NodeHostnameError{Problems: problems, issues: issues}, short, warnings
}

// minimegaWildcardVM is the name minimega takes for every VM, which phenix
// refuses as a hostname (see [v1.CheckHostname]).
const minimegaWildcardVM = "all"

// hostnameCode is the code of what phenix makes of a hostname it refuses
// (refused) or warns about (see [checkHostname]), in the order phenix checks
// them: one character, "all", all digits, and else "phenix" on a Windows
// node; for a warning, another casing of "all", and else "phenix" on another
// node.
func hostnameCode(hostname string, refused bool) Code {
	switch {
	case refused && isShortHostname(hostname):
		return CodeNodeHostnameShort
	case refused && hostname == minimegaWildcardVM:
		return CodeNodeHostnameReserved
	case refused && hostname != "" && strings.Trim(hostname, "0123456789") == "":
		return CodeNodeHostnameNumeric
	case refused:
		return CodeNodeHostnameWindows
	case strings.EqualFold(hostname, minimegaWildcardVM):
		return CodeNodeHostnameReservedCase
	default:
		return CodeNodeHostnamePhenix
	}
}

// checkHostname reports what phenix makes of the hostname of a node it
// starts, whose os_type is osType: an error for a hostname phenix refuses, a
// single character, which phenix's schema refuses, or one phenix stores but
// refuses when it creates an experiment from the node (see
// [v1.CheckHostname]): "all", all digits, or "phenix" on a Windows node. It
// returns the warning phenix logs about a hostname it accepts.
func checkHostname(hostname, osType string) (string, error) {
	if isShortHostname(hostname) {
		return "", fmt.Errorf(
			"hostname '%s' is 1 character long: phenix requires hostnames of at least 2 characters, "+
				"as VyOS, Vyatta and Windows do",
			hostname,
		)
	}

	return v1.CheckHostname(hostname, osType)
}

// isShortHostname reports whether hostname is a single character, as
// phenix's schema counts characters.
func isShortHostname(hostname string) bool {
	return utf8.RuneCountInString(hostname) == 1
}

// startedNodes calls visit with the position among the spec's nodes, the
// hostname and the os_type of each node of a topology spec that phenix
// starts: every node but the external ones.
func startedNodes(spec map[string]any, visit func(position int, hostname, osType string)) {
	nodes, _ := spec[keyNodes].([]any)

	for position, entry := range nodes {
		node, ok := entry.(map[string]any)
		if !ok || node["external"] != nil {
			continue
		}

		visit(position, specString(node, "general", "hostname"), specString(node, "hardware", "os_type"))
	}
}

// interfaceLabels names each interface of a node spec in a message: by its
// quoted name, or by its position when it has none or shares it with another
// (#2, "eth0" (#3)).
func interfaceLabels(ifaces []any) []string {
	names := make(map[string]int, len(ifaces))

	for _, iface := range ifaces {
		names[interfaceName(iface)]++
	}

	labels := make([]string, len(ifaces))

	for index, iface := range ifaces {
		name := interfaceName(iface)

		switch {
		case strings.TrimSpace(name) == "":
			labels[index] = fmt.Sprintf("#%d", index+1)
		case names[name] > 1:
			labels[index] = fmt.Sprintf("%q (#%d)", name, index+1)
		default:
			labels[index] = strconv.Quote(name)
		}
	}

	return labels
}

// addressUsers are the interfaces that use one IP or MAC address on one
// network, in document order.
type addressUsers struct {
	// address names the address and its network in a message:
	// `IP address 10.0.0.5 on VLAN "EXP"`.
	address string
	// users names each interface: `interface "eth0" of device "web"`.
	users []string
	// own counts the interfaces of devices that are not included.
	own int
	// issue is the issue of the address, of its code, located at the first
	// interface of a device that is not included that uses it.
	issue Issue
}

// The keys of a spec interface that hold the addresses
// [Document.checkInterfaceAddresses] compares, and the path below a device
// node of its hostname, where an issue about the hostname is.
const (
	specAddressKey = "address"
	specMACKey     = "mac"
	hostnamePath   = "device.hostname"
)

// addressUse is one interface's use of an IP or MAC address (see
// [Document.checkInterfaceAddresses]).
type addressUse struct {
	// key is the address and its network as they are compared.
	key addressKey
	// address names the address and its network in a message.
	address string
	// user names the interface in a message.
	user     string
	included bool
	// code is the code of a shared address of this kind.
	code Code
	// path, nodeID and field locate the interface's address field.
	path, nodeID, field string
}

// addressKey is what two interfaces share when their addresses clash: an
// address of one kind on one network (see [interfaceNetwork]).
type addressKey struct {
	// kind is "ip" or "mac".
	kind string
	// address is the address as [interfaceIP] or [interfaceMAC] reads it.
	address string
	bridge  string
	vlan    string
}

// checkInterfaceAddresses refuses a document in which two interfaces on the
// same network use the same IP address or the same MAC address: phenix stores
// such a topology, but the addresses clash once the experiment runs. Each
// interface is on the network publishing puts it on (see
// [interfaceNetwork]): interfaces on different VLANs, or on VLANs of one name
// on different bridges, are on networks of their own, which may use the same
// addresses, as isolated networks often do and as minimega allows (it compares
// VLANs before it reports a MAC address twice). Every device counts, including
// an external device's IP addresses and the devices of included topologies,
// which phenix merges into the experiment; an address only included devices
// use is their topology's to fix. An external device's MAC addresses do not
// count: phenix does not start it, and its schema has no MAC. IP addresses are
// compared parsed (see [interfaceIP]), and MAC addresses in any case and with
// any separators (see [interfaceMAC]). The error names each address, its
// network and the interfaces that use it, in document order.
func (d *Document) checkInterfaceAddresses() error {
	var (
		shared []*addressUsers
		byKey  = map[addressKey]*addressUsers{}
	)

	use := func(found addressUse) {
		entry := byKey[found.key]
		if entry == nil {
			entry = &addressUsers{address: found.address, users: nil, own: 0, issue: NewIssue(found.code, "", "")}
			byKey[found.key] = entry
			shared = append(shared, entry)
		}

		entry.users = append(entry.users, found.user)

		if found.included {
			return
		}

		if entry.own == 0 {
			entry.issue.Path, entry.issue.NodeID, entry.issue.Field = found.path, found.nodeID, found.field
		}

		entry.own++
	}

	d.eachAddressUse(use)

	var (
		problems []string
		issues   []Issue
	)

	for _, entry := range shared {
		if len(entry.users) < 2 || entry.own == 0 {
			continue
		}

		first, second, more := entry.users[0], entry.users[1], len(entry.users[2:])
		users := first + " and " + second

		switch {
		case more == 1:
			users = first + ", " + second + " and 1 more interface"
		case more > 1:
			users = fmt.Sprintf("%s, %s and %d more interfaces", first, second, more)
		}

		problem := fmt.Sprintf("%s is used by %s", entry.address, users)
		entry.issue.Message = problem

		problems = append(problems, problem)
		issues = append(issues, entry.issue)
	}

	if len(problems) == 0 {
		return nil
	}

	return &InterfaceAddressError{Problems: problems, issues: issues}
}

// eachAddressUse calls use with each IP address and each MAC address an
// interface of a device of the document uses, in document order, on the
// network publishing puts the interface on, as
// [Document.checkInterfaceAddresses] compares them: an external device's MAC
// addresses are left out.
func (d *Document) eachAddressUse(use func(addressUse)) {
	networks := d.handleNetworks()

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind != NodeKindDevice || node.Device == nil {
			continue
		}

		spec, err := normalizeSpecMap(node.Device.Spec)
		if err != nil {
			continue // ToTopology refuses it first
		}

		// Each interface's VLAN as publishing writes it. The spec is a copy,
		// and the warnings are ToTopology's to give.
		connectInterfaces(node, i, spec, networks)

		ifaces := specNodeInterfaces(spec)
		labels := interfaceLabels(ifaces)
		included := node.Device.IncludedFrom != ""
		external := spec["external"] != nil

		for index, entry := range ifaces {
			iface, ok := entry.(map[string]any)
			if !ok {
				continue
			}

			user := fmt.Sprintf("interface %s of device %q", labels[index], node.Device.Hostname)
			bridge, vlan := interfaceNetwork(iface)
			network := networkPhrase(bridge, vlan)

			// found is the interface's use of the address, of the kind ("ip"
			// or "mac") a message calls name, held in its key specKey.
			found := func(kind, address, name string, code Code, specKey string) addressUse {
				return addressUse{
					key:      addressKey{kind: kind, address: address, bridge: bridge, vlan: vlan},
					address:  name + " " + address + network,
					user:     user,
					included: included,
					code:     code,
					path:     fmt.Sprintf("nodes[%d].device.spec.network.interfaces[%d].%s", i, index, specKey),
					nodeID:   node.ID,
					field:    fmt.Sprintf("spec.network.interfaces.%d.%s", index, specKey),
				}
			}

			if addr, ok := interfaceIP(iface); ok {
				use(found("ip", addr.String(), "IP address", CodeInterfaceIPShared, specAddressKey))
			}

			if mac, ok := interfaceMAC(iface); ok && !external {
				use(found("mac", mac.String(), "MAC address", CodeInterfaceMACShared, specMACKey))
			}
		}
	}
}

// interfaceIP reads the IP address a spec interface entry uses, as Go parses
// it, without a zone, and with an IPv4 address mapped into IPv6 as the IPv4
// address. A prefix length typed after it is ignored. It reports none for an
// interface that asks DHCP for its address, for one phenix brings up with no
// address (proto manual), and for an address that is blank or does not parse,
// which is the schema's to report.
//
// A manual interface's address is left out although the vrouter app's Vyatta
// and VyOS configuration assigns it: phenix's schema describes manual as no
// address, its Linux and Windows startup scripts and minirouter assign none,
// and the Builder's Inspector does not show it. An interface with qinq set
// counts: minirouter, which the Builder's Router and Firewall templates use,
// assigns its address, and so does Vyatta.
func interfaceIP(iface map[string]any) (netip.Addr, bool) {
	proto, _ := iface["proto"].(string)

	switch strings.ToLower(trimASCIISpace(proto)) {
	case "dhcp", "manual":
		return netip.Addr{}, false
	}

	text, _ := iface[specAddressKey].(string)
	text, _, _ = strings.Cut(text, "/")

	addr, err := netip.ParseAddr(trimASCIISpace(text))
	if err != nil {
		return netip.Addr{}, false
	}

	return addr.WithZone("").Unmap(), true
}

// interfaceMAC reads the MAC address a spec interface entry uses, in any case
// and with any separators: aa:bb:cc:dd:ee:ff, AA-BB-CC-DD-EE-FF and
// aabb.ccdd.eeff are one address. It reports none for a blank MAC, for which
// minimega makes one, and for one that is not twelve hex digits, which is the
// schema's to report.
func interfaceMAC(iface map[string]any) (net.HardwareAddr, bool) {
	const length = 6 // bytes of a MAC address

	text, _ := iface[specMACKey].(string)

	mac, err := hex.DecodeString(strings.NewReplacer(":", "", "-", "", ".", "").Replace(trimASCIISpace(text)))
	if err != nil || len(mac) != length {
		return nil, false
	}

	return net.HardwareAddr(mac), true
}

// defaultBridgeName is the bridge an interface names to be on the
// experiment's default bridge, as a blank bridge does: phenix replaces both
// with that bridge (see v1.Network.SetDefaults).
const defaultBridgeName = "phenix"

// interfaceNetwork names the network a spec interface entry is on, once
// connecting it on the canvas has set its VLAN (see [connectInterfaces]): the
// bridge, "" for the experiment's default one, and the VLAN, without the
// white space around it, "" for none. A bridge is compared as it is written,
// so one that names the experiment's default bridge counts as another bridge;
// a VLAN as it is written too, as phenix matches VLAN names exactly.
// Interfaces without a VLAN, which publishing refuses unless their device is
// external, are all on one network of their own.
func interfaceNetwork(iface map[string]any) (string, string) {
	bridge, _ := iface["bridge"].(string)
	if bridge == defaultBridgeName {
		bridge = ""
	}

	vlan, _ := iface["vlan"].(string)

	return bridge, strings.TrimSpace(vlan)
}

// networkPhrase names the network [interfaceNetwork] returns in a message,
// after an address: ` on VLAN "EXP"`, ` on VLAN "EXP" of bridge "lab"`,
// ` without a VLAN`.
func networkPhrase(bridge, vlan string) string {
	switch {
	case vlan == "" && bridge == "":
		return " without a VLAN"
	case vlan == "":
		return fmt.Sprintf(" on bridge %q without a VLAN", bridge)
	case bridge == "":
		return fmt.Sprintf(" on VLAN %q", vlan)
	default:
		return fmt.Sprintf(" on VLAN %q of bridge %q", vlan, bridge)
	}
}

// trimASCIISpace trims the ASCII whitespace around an address or a proto. The
// editor trims the same characters (trimASCIISpace in validate.js), so both
// read an address alike: [strings.TrimSpace] and JavaScript's trim each trim a
// character the other keeps (U+0085 and U+FEFF).
func trimASCIISpace(text string) string {
	return strings.Trim(text, " \t\n\v\f\r")
}

// specInterfaceVLAN reports whether a spec interface entry names a VLAN and, when
// it does not, whether its vlan is missing or null rather than blank. An entry
// of the wrong shape, or a VLAN that is not a string, is left to the schema.
func specInterfaceVLAN(iface any) (bool, bool) {
	asMap, ok := iface.(map[string]any)
	if !ok {
		return true, false
	}

	value := asMap["vlan"]
	if value == nil {
		return false, true
	}

	vlan, ok := value.(string)

	return !ok || strings.TrimSpace(vlan) != "", false
}

// SpecV1 decodes the mapped topology spec into the versioned phenix topology
// spec. Callers that only need the stored representation should use
// [Topology.Spec] directly, which preserves keys unknown to v1.
//
// It decodes weakly, as phenix does (see types.DecodeTopologyFromConfig): the
// schema allows a string for vcpus and memory, and one address for dns.
func (t *Topology) SpecV1() (*v1.TopologySpec, error) {
	var spec v1.TopologySpec

	if err := mapstructure.WeakDecode(t.Spec, &spec); err != nil {
		return nil, fmt.Errorf("decoding topology spec: %w", err)
	}

	return &spec, nil
}

// handleNetworks maps each connected interface handle onto its network.
func (d *Document) handleNetworks() map[string]*Network {
	switchNetworks := make(map[string]*Network)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind == NodeKindSwitch && node.Switch != nil {
			switchNetworks[node.ID] = d.NetworkByID(node.Switch.NetworkID)
		}
	}

	handles := make(map[string]*Network)

	for i := range d.Edges {
		edge := &d.Edges[i]

		source := d.NodeByID(edge.SourceNodeID)
		target := d.NodeByID(edge.TargetNodeID)

		if source == nil || target == nil {
			continue
		}

		device, handle, switchNode, ok := edgeEndpoints(
			source, edge.SourceHandleID, target, edge.TargetHandleID,
		)
		if !ok || device == nil {
			continue
		}

		if network := switchNetworks[switchNode.ID]; network != nil {
			handles[handle] = network
		}
	}

	return handles
}

// deviceSpec produces the topology node spec of a device node, the one at
// index among the document's nodes, which locates its warnings.
func deviceSpec(node *Node, index int, handleNetworks map[string]*Network) (map[string]any, []Issue, error) {
	spec, err := normalizeSpecMap(node.Device.Spec)
	if err != nil {
		return nil, nil, err
	}

	if spec == nil {
		spec = map[string]any{}
	}

	var warnings []Issue

	if existing := specString(spec, "general", "hostname"); existing != "" &&
		existing != node.Device.Hostname {
		warnings = append(warnings, deviceIssue(
			CodeDeviceHostnameMismatch, node, index, "device.spec.general.hostname", fmt.Sprintf(
				"device %q carries a node spec with hostname %q; the device hostname wins",
				node.Device.Hostname, existing,
			),
		))
	}

	if !specSetString(spec, node.Device.Hostname, "general", "hostname") {
		return nil, nil, fmt.Errorf("node spec key %q is not an object", "general")
	}

	warnings = append(warnings, connectInterfaces(node, index, spec, handleNetworks)...)

	return spec, warnings, nil
}

// deviceIssue is an issue of code about the device node at index among the
// document's nodes, at path below it.
func deviceIssue(code Code, node *Node, index int, path, message string) Issue {
	issue := NewIssue(code, fmt.Sprintf("nodes[%d].%s", index, path), message)
	issue.NodeID = node.ID

	return issue
}

// connectInterfaces sets the VLAN of each interface of spec, the node spec of
// the device node at index among the document's nodes, whose connection point
// is connected to a network to that network's name, as publishing writes it.
// It returns a warning for each connection whose interface the spec does not
// have, which publishing drops.
func connectInterfaces(node *Node, index int, spec map[string]any, handleNetworks map[string]*Network) []Issue {
	var (
		ifaces   = specNodeInterfaces(spec)
		warnings []Issue
	)

	for position, handle := range node.Device.Interfaces {
		network, ok := handleNetworks[handle.ID]
		if !ok || network == nil {
			continue
		}

		iface := findInterface(ifaces, handle.Name)
		if iface == nil {
			warnings = append(warnings, deviceIssue(
				CodeInterfaceNameUnmatched, node, index, fmt.Sprintf("device.interfaces[%d].name", position), fmt.Sprintf(
					"device %q is connected to network %q through interface %q, "+
						"but the node spec has no such interface; the connection was dropped",
					node.Device.Hostname, network.Name, handle.Name,
				),
			))

			continue
		}

		iface["vlan"] = network.Name
	}

	return warnings
}

// findInterface locates a spec interface by name, preferring an exact match and
// falling back to a case-insensitive one.
func findInterface(ifaces []any, name string) map[string]any {
	var fallback map[string]any

	for _, iface := range ifaces {
		asMap, ok := iface.(map[string]any)
		if !ok {
			continue
		}

		ifaceName, _ := asMap["name"].(string)

		if ifaceName == name {
			return asMap
		}

		if fallback == nil && foldKey(ifaceName) == foldKey(name) {
			fallback = asMap
		}
	}

	return fallback
}
