package builder

import (
	"fmt"
	"maps"
	"slices"
	"strconv"
	"strings"

	"github.com/mitchellh/mapstructure"

	"phenix/store"
	"phenix/types"
	v1 "phenix/types/version/v1"
)

// TopologyAPIVersion is the config apiVersion of topologies generated by this
// package.
const TopologyAPIVersion = "phenix.sandia.gov/v1"

// Topology is the authoritative projection of a builder document onto phenix
// configuration data.
type Topology struct {
	// Spec is the topology spec in the stored representation, ready to be used
	// as store.Config.Spec.
	Spec map[string]any
	// VLANAliases maps network names to their integer VLAN alias, ready to be
	// used as an experiment's spec.vlans.aliases.
	VLANAliases map[string]int
	// Warnings collects non-fatal issues found while mapping the document.
	Warnings []string
}

// InterfaceVLANError is returned, wrapped, by [Document.PublishTopologyConfig]
// and [Document.ValidateTopologyProjection] for a projection in which
// interfaces have no VLAN (see [checkInterfaceVLANs]).
type InterfaceVLANError struct {
	// Problems names each device and interface, and what to do about it.
	Problems []string
}

func (e *InterfaceVLANError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// ToTopology maps a builder document onto a phenix topology spec and the
// experiment VLAN alias map.
//
// Mapping rules:
//
//   - switch, note, and group nodes are omitted; they carry no phenix
//     semantics,
//   - devices from included topologies ([Device.IncludedFrom]) are omitted,
//     and the document's includeTopologies are written instead, so phenix
//     merges those devices back in and a publish never duplicates them,
//   - each other device contributes its complete node spec verbatim, including
//     general.description and any keys unknown to this package,
//   - an interface whose handle is connected to a network has its VLAN set to
//     that network's canonical name,
//   - interfaces that are not connected are preserved unchanged (including any
//     VLAN they already declare, or none, which [Document.PublishTopologyConfig]
//     refuses),
//   - every network carrying an integer alias contributes a VLAN alias.
//
// The document is validated first; an invalid document is never mapped.
func (d *Document) ToTopology() (*Topology, error) {
	if err := d.Validate(); err != nil {
		return nil, err
	}

	handleNetworks := d.handleNetworks()

	var (
		nodes    = make([]any, 0, len(d.Nodes))
		warnings []string
	)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind != NodeKindDevice || node.Device == nil || node.Device.IncludedFrom != "" {
			continue
		}

		spec, nodeWarnings, err := deviceSpec(node, handleNetworks)
		if err != nil {
			return nil, fmt.Errorf("mapping device %q: %w", node.Device.Hostname, err)
		}

		warnings = append(warnings, nodeWarnings...)
		nodes = append(nodes, spec)
	}

	aliases := make(map[string]int)

	for i := range d.Networks {
		network := &d.Networks[i]
		if network.Alias != nil {
			aliases[network.Name] = *network.Alias
		}
	}

	spec := map[string]any{keyNodes: nodes}
	if d.Source != nil && len(d.Source.IncludeTopologies) > 0 {
		spec["includeTopologies"] = slices.Clone(d.Source.IncludeTopologies)
	}

	return &Topology{
		Spec:        spec,
		VLANAliases: aliases,
		Warnings:    warnings,
	}, nil
}

// ToTopologyConfig maps the document onto a stored Topology config named name.
func (d *Document) ToTopologyConfig(name string) (*store.Config, []string, error) {
	topology, err := d.ToTopology()
	if err != nil {
		return nil, nil, err
	}

	config, err := store.NewConfig("topology/" + name)
	if err != nil {
		return nil, nil, fmt.Errorf("creating topology config: %w", err)
	}

	config.Version = TopologyAPIVersion
	config.Spec = topology.Spec

	return config, topology.Warnings, nil
}

// ValidateTopologyProjection runs the checks publishing makes against the
// document's projection, so a caller about to publish a topology can
// authoritatively verify complete node specs: every interface of a device
// phenix starts has a VLAN (see [checkInterfaceVLANs]), and the spec passes
// the existing phenix topology schema validation.
//
// This is deliberately separate from [Document.Validate], which validates the
// draft working copy: a working copy may legitimately contain interfaces that
// are not yet connected to a network and have no VLAN, which a published
// topology may not.
//
// It calls types.ValidateConfigSpec, which validates the config envelope and
// the versioned topology schema. It does not resolve included topologies from
// the store, so there is no recursion back into this package.
func (d *Document) ValidateTopologyProjection(name string) ([]string, error) {
	config, warnings, err := d.ToTopologyConfig(name)
	if err != nil {
		return nil, err
	}

	if err := validateProjection(config); err != nil {
		return warnings, err
	}

	return warnings, nil
}

// PublishTopologyConfig projects the document onto a topology config and
// validates it as [Document.ValidateTopologyProjection] does. It is the entry
// point for callers that intend to store the result.
func (d *Document) PublishTopologyConfig(name string) (*store.Config, []string, error) {
	config, warnings, err := d.ToTopologyConfig(name)
	if err != nil {
		return nil, nil, err
	}

	if err := validateProjection(config); err != nil {
		return nil, warnings, err
	}

	return config, warnings, nil
}

// validateProjection runs the checks of a topology config about to be
// published: interface VLANs first, as their error names what to fix, then the
// phenix topology schema.
func validateProjection(config *store.Config) error {
	if err := checkInterfaceVLANs(config.Spec); err != nil {
		return fmt.Errorf("validating topology projection: %w", err)
	}

	if err := types.ValidateConfigSpec(*config); err != nil {
		return fmt.Errorf("validating topology projection: %w", err)
	}

	return nil
}

// checkInterfaceVLANs refuses a topology spec in which an interface of a node
// phenix starts has no VLAN: none at all, or an empty one. The phenix topology
// schema requires only the vlan key, so phenix stores such a topology, but
// minimega refuses the interface when the experiment starts ("VLAN must be
// non-empty string"). A VLAN that names no network of the document is kept:
// phenix allocates VLANs by name. External nodes are not started, and need
// none. The error names each device and interface to fix: an interface by
// its position when it has no name, or shares it with another.
func checkInterfaceVLANs(spec map[string]any) error {
	nodes, _ := spec[keyNodes].([]any)

	var problems []string

	for _, entry := range nodes {
		node, ok := entry.(map[string]any)
		if !ok || node["external"] != nil {
			continue
		}

		hostname := specString(node, "general", "hostname")
		ifaces := specNodeInterfaces(node)
		names := make(map[string]int, len(ifaces))

		for _, iface := range ifaces {
			names[interfaceName(iface)]++
		}

		for index, iface := range ifaces {
			if hasVLAN(iface) {
				continue
			}

			name := interfaceName(iface)
			label := strconv.Quote(name)

			switch {
			case strings.TrimSpace(name) == "":
				label = fmt.Sprintf("#%d", index+1)
			case names[name] > 1:
				label = fmt.Sprintf("%q (#%d)", name, index+1)
			}

			problems = append(problems, fmt.Sprintf(
				"interface %s of device %q has no VLAN: connect it to a network, or type a VLAN for it",
				label, hostname,
			))
		}
	}

	if len(problems) == 0 {
		return nil
	}

	return &InterfaceVLANError{Problems: problems}
}

// hasVLAN reports whether a spec interface entry names a VLAN. An entry of the
// wrong shape, or a VLAN that is not a string, is left to the schema.
func hasVLAN(iface any) bool {
	asMap, ok := iface.(map[string]any)
	if !ok {
		return true
	}

	value := asMap["vlan"]
	if value == nil {
		return false
	}

	vlan, ok := value.(string)

	return !ok || strings.TrimSpace(vlan) != ""
}

// SpecV1 decodes the mapped topology spec into the versioned phenix topology
// spec. Callers that only need the stored representation should use
// [Topology.Spec] directly, which preserves keys unknown to v1.
//
// It decodes weakly, as phenix does (see types.DecodeTopologyFromConfig): the
// schema allows a string for vcpus and memory, and one address for dns.
func (t *Topology) SpecV1() (*v1.TopologySpec, error) {
	var spec v1.TopologySpec

	if err := mapstructure.WeakDecode(t.Spec, &spec); err != nil {
		return nil, fmt.Errorf("decoding topology spec: %w", err)
	}

	return &spec, nil
}

// handleNetworks maps each connected interface handle onto its network.
func (d *Document) handleNetworks() map[string]*Network {
	switchNetworks := make(map[string]*Network)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind == NodeKindSwitch && node.Switch != nil {
			switchNetworks[node.ID] = d.NetworkByID(node.Switch.NetworkID)
		}
	}

	handles := make(map[string]*Network)

	for i := range d.Edges {
		edge := &d.Edges[i]

		source := d.NodeByID(edge.SourceNodeID)
		target := d.NodeByID(edge.TargetNodeID)

		if source == nil || target == nil {
			continue
		}

		device, handle, switchNode, ok := edgeEndpoints(
			source, edge.SourceHandleID, target, edge.TargetHandleID,
		)
		if !ok || device == nil {
			continue
		}

		if network := switchNetworks[switchNode.ID]; network != nil {
			handles[handle] = network
		}
	}

	return handles
}

// deviceSpec produces the topology node spec of a device node.
func deviceSpec(node *Node, handleNetworks map[string]*Network) (map[string]any, []string, error) {
	spec, err := normalizeSpecMap(node.Device.Spec)
	if err != nil {
		return nil, nil, err
	}

	if spec == nil {
		spec = map[string]any{}
	}

	var warnings []string

	if existing := specString(spec, "general", "hostname"); existing != "" &&
		existing != node.Device.Hostname {
		warnings = append(warnings, fmt.Sprintf(
			"device %q carries a node spec with hostname %q; the device hostname wins",
			node.Device.Hostname, existing,
		))
	}

	if !specSetString(spec, node.Device.Hostname, "general", "hostname") {
		return nil, nil, fmt.Errorf("node spec key %q is not an object", "general")
	}

	ifaces := specNodeInterfaces(spec)

	for _, handle := range node.Device.Interfaces {
		network, ok := handleNetworks[handle.ID]
		if !ok || network == nil {
			continue
		}

		iface := findInterface(ifaces, handle.Name)
		if iface == nil {
			warnings = append(warnings, fmt.Sprintf(
				"device %q is connected to network %q through interface %q, "+
					"but the node spec has no such interface; the connection was dropped",
				node.Device.Hostname, network.Name, handle.Name,
			))

			continue
		}

		iface["vlan"] = network.Name
	}

	return spec, warnings, nil
}

// findInterface locates a spec interface by name, preferring an exact match and
// falling back to a case-insensitive one.
func findInterface(ifaces []any, name string) map[string]any {
	var fallback map[string]any

	for _, iface := range ifaces {
		asMap, ok := iface.(map[string]any)
		if !ok {
			continue
		}

		ifaceName, _ := asMap["name"].(string)

		if ifaceName == name {
			return asMap
		}

		if fallback == nil && foldKey(ifaceName) == foldKey(name) {
			fallback = asMap
		}
	}

	return fallback
}

// SortedVLANAliasNames returns the alias names in deterministic order.
func (t *Topology) SortedVLANAliasNames() []string {
	return slices.Sorted(maps.Keys(t.VLANAliases))
}
