package builder

import (
	"encoding/hex"
	"fmt"
	"net"
	"net/netip"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/mitchellh/mapstructure"

	"phenix/store"
	"phenix/types"
	v1 "phenix/types/version/v1"
)

// TopologyAPIVersion is the config apiVersion of topologies generated by this
// package.
const TopologyAPIVersion = "phenix.sandia.gov/v1"

// Topology is the authoritative projection of a builder document onto phenix
// configuration data.
type Topology struct {
	// Spec is the topology spec in the stored representation, ready to be used
	// as store.Config.Spec.
	Spec map[string]any
	// VLANAliases maps network names to their integer VLAN alias, ready to be
	// used as an experiment's spec.vlans.aliases.
	VLANAliases map[string]int
	// Warnings collects non-fatal issues found while mapping the document.
	Warnings []string
}

// TopologyExport is the topology config a document publishes as (see
// [Document.ExportTopologyConfig]).
type TopologyExport struct {
	// Config is the topology config publishing stores.
	Config *store.Config
	// Warnings collects non-fatal issues found while mapping the document.
	Warnings []string
	// PublishBlockers are why publishing refuses Config although phenix's
	// config validation accepts it, one error per check in the order
	// publishing makes them (see [Document.PublishTopologyConfig]), or none.
	PublishBlockers []error
}

// InterfaceVLANError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a projection in which interfaces have no VLAN (see
// [checkInterfaceVLANs]), and is one of the [TopologyExport.PublishBlockers]
// of such a projection.
type InterfaceVLANError struct {
	// Problems names each device and interface, and what to do about it.
	Problems []string
}

func (e *InterfaceVLANError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// InterfaceAddressError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a document in which interfaces use the same IP or MAC address (see
// [Document.checkInterfaceAddresses]), and is one of the
// [TopologyExport.PublishBlockers] of such a document.
type InterfaceAddressError struct {
	// Problems names each address and the interfaces that use it.
	Problems []string
}

func (e *InterfaceAddressError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// NodeHostnameError is returned, wrapped, by [Document.PublishTopologyConfig]
// for a projection with hostnames phenix refuses (see [checkHostnames]), and
// is one of the [TopologyExport.PublishBlockers] of such a projection.
type NodeHostnameError struct {
	// Problems names each hostname and why phenix refuses it.
	Problems []string
}

func (e *NodeHostnameError) Error() string {
	return strings.Join(e.Problems, "; ")
}

// ToTopology maps a builder document onto a phenix topology spec and the
// experiment VLAN alias map.
//
// Mapping rules:
//
//   - switch, note, and group nodes are omitted; they carry no phenix
//     semantics,
//   - devices from included topologies ([Device.IncludedFrom]) are omitted,
//     and the document's includeTopologies are written instead, so phenix
//     merges those devices back in and a publish never duplicates them,
//   - each other device contributes its complete node spec verbatim, including
//     general.description and any keys unknown to this package,
//   - an interface whose handle is connected to a network has its VLAN set to
//     that network's canonical name,
//   - interfaces that are not connected are preserved unchanged (including any
//     VLAN they already declare, or none, which [Document.PublishTopologyConfig]
//     refuses),
//   - every network carrying an integer alias contributes a VLAN alias.
//
// The document is validated first; an invalid document is never mapped.
func (d *Document) ToTopology() (*Topology, error) {
	if err := d.Validate(); err != nil {
		return nil, err
	}

	handleNetworks := d.handleNetworks()

	var (
		nodes    = make([]any, 0, len(d.Nodes))
		warnings []string
	)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind != NodeKindDevice || node.Device == nil || node.Device.IncludedFrom != "" {
			continue
		}

		spec, nodeWarnings, err := deviceSpec(node, handleNetworks)
		if err != nil {
			return nil, fmt.Errorf("mapping device %q: %w", node.Device.Hostname, err)
		}

		warnings = append(warnings, nodeWarnings...)
		nodes = append(nodes, spec)
	}

	aliases := make(map[string]int)

	for i := range d.Networks {
		network := &d.Networks[i]
		if network.Alias != nil {
			aliases[network.Name] = *network.Alias
		}
	}

	spec := map[string]any{keyNodes: nodes}
	if d.Source != nil && len(d.Source.IncludeTopologies) > 0 {
		spec["includeTopologies"] = slices.Clone(d.Source.IncludeTopologies)
	}

	return &Topology{
		Spec:        spec,
		VLANAliases: aliases,
		Warnings:    warnings,
	}, nil
}

// ToTopologyConfig maps the document onto a stored Topology config named name.
func (d *Document) ToTopologyConfig(name string) (*store.Config, []string, error) {
	topology, err := d.ToTopology()
	if err != nil {
		return nil, nil, err
	}

	config, err := topologyConfig(name, topology)
	if err != nil {
		return nil, nil, err
	}

	return config, topology.Warnings, nil
}

// topologyConfig is the Topology config named name holding the projection's
// spec (the same map, not a copy).
func topologyConfig(name string, topology *Topology) (*store.Config, error) {
	config, err := store.NewConfig("topology/" + name)
	if err != nil {
		return nil, fmt.Errorf("creating topology config: %w", err)
	}

	config.Version = TopologyAPIVersion
	config.Spec = topology.Spec

	return config, nil
}

// PublishTopologyConfig projects the document onto a topology config and runs
// the checks publishing makes, so a caller about to publish a topology can
// authoritatively verify complete node specs: every interface of a device
// phenix starts has a VLAN (see [checkInterfaceVLANs]), no two interfaces use
// one IP or MAC address (see [Document.checkInterfaceAddresses]), phenix
// accepts every hostname (see [checkHostnames]), and the spec passes the
// existing phenix topology schema validation (types.ValidateConfigSpec, which
// does not resolve included topologies from the store).
//
// This is deliberately separate from [Document.Validate], which validates the
// draft working copy: a working copy may legitimately contain interfaces that
// are not yet connected to a network and have no VLAN, or that share an
// address, or a hostname imported from a topology older phenix stored, which
// a published topology may not.
//
// It is the entry point for callers that intend to store the result. What
// only publishing refuses (see [Document.projectTopology]) is reported first,
// whatever else phenix's config validation finds, as its errors name what to
// fix: the first check that fails, so interfaces without a VLAN before
// addresses interfaces share, and those before hostnames phenix refuses.
func (d *Document) PublishTopologyConfig(name string) (*store.Config, []string, error) {
	config, _, warnings, err := d.PublishTopology(name)

	return config, warnings, err
}

// PublishTopology is [Document.PublishTopologyConfig] that also returns the
// projection the config holds, for a publisher that needs more of it (its
// VLAN aliases, say) without projecting the document again. The config's
// spec is the projection's, so neither may be changed while the other is
// in use.
func (d *Document) PublishTopology(name string) (*store.Config, *Topology, []string, error) {
	projection, err := d.projectTopology(name)
	if err != nil {
		return nil, nil, nil, err
	}

	if len(projection.blockers) > 0 {
		return nil, nil, projection.warnings, projection.blockers[0]
	}

	if projection.schema != nil {
		return nil, nil, projection.warnings, projection.schema
	}

	return projection.config, projection.topology, projection.warnings, nil
}

// ExportTopologyConfig projects the document onto a topology config and runs
// the checks of [Document.PublishTopologyConfig], for a caller that hands the
// config out rather than stores it. One that only publishing refuses, as an
// interface has a blank VLAN, interfaces share an address, or phenix would
// refuse a hostname when it creates an experiment, is returned with every
// such error, the one PublishTopologyConfig returns first, as its
// PublishBlockers.
//
// A projection that fails phenix's config validation is refused. When an
// interface's vlan key is missing or null, or a hostname is a single
// character, which the schema refuses too, the error is the one publishing
// makes of it, naming the interfaces or the hostnames. Otherwise it is the
// schema's own error: blank VLANs, shared addresses and the hostnames phenix
// refuses only when it creates an experiment, which the schema accepts, are
// not why the config cannot be exported.
func (d *Document) ExportTopologyConfig(name string) (*TopologyExport, error) {
	projection, err := d.projectTopology(name)
	if err != nil {
		return nil, err
	}

	if projection.schema != nil {
		switch {
		case projection.absentVLANs != nil:
			return nil, projection.absentVLANs
		case projection.shortHostnames != nil:
			return nil, projection.shortHostnames
		default:
			return nil, projection.schema
		}
	}

	return &TopologyExport{
		Config:          projection.config,
		Warnings:        projection.warnings,
		PublishBlockers: projection.blockers,
	}, nil
}

// topologyProjection is a document projected onto a topology config, with
// what the checks of publishing found.
type topologyProjection struct {
	config *store.Config
	// topology is the projection config was made from; config.Spec is its
	// Spec.
	topology *Topology
	warnings []string
	// blockers are the checks only publishing makes that config fails, in the
	// order publishing makes them (see [Document.projectTopology]).
	blockers []error
	// absentVLANs is the blocker naming the interfaces without a VLAN when
	// one of them has no vlan key, or a null one, which phenix's schema
	// refuses too, and nil otherwise.
	absentVLANs error
	// shortHostnames is the blocker naming the hostnames phenix refuses when
	// one of them is a single character, which phenix's schema refuses too,
	// and nil otherwise.
	shortHostnames error
	// schema is why phenix's config validation refuses config, or nil.
	schema error
}

// projectTopology projects the document onto a topology config named name
// and runs every check of publishing on it. It is the one place that decides
// what publishing refuses although phenix's config validation may accept it,
// which [Document.PublishTopologyConfig] refuses and
// [Document.ExportTopologyConfig] reports, in this order: interfaces without
// a VLAN (see [checkInterfaceVLANs]), then addresses interfaces share (see
// [Document.checkInterfaceAddresses]), then hostnames phenix refuses (see
// [checkHostnames]), whose warnings it adds to the projection's. Then it runs
// the phenix topology schema.
func (d *Document) projectTopology(name string) (*topologyProjection, error) {
	topology, err := d.ToTopology()
	if err != nil {
		return nil, err
	}

	config, err := topologyConfig(name, topology)
	if err != nil {
		return nil, err
	}

	projection := &topologyProjection{
		config: config, topology: topology, warnings: slices.Clone(topology.Warnings),
		blockers: nil, absentVLANs: nil, shortHostnames: nil, schema: nil,
	}

	if vlans, absent := checkInterfaceVLANs(config.Spec); vlans != nil {
		blocker := fmt.Errorf("validating topology projection: %w", vlans)
		projection.blockers = append(projection.blockers, blocker)

		if absent {
			projection.absentVLANs = blocker
		}
	}

	if addresses := d.checkInterfaceAddresses(); addresses != nil {
		projection.blockers = append(projection.blockers, fmt.Errorf("validating topology projection: %w", addresses))
	}

	hostnames, short, hostnameWarnings := checkHostnames(config.Spec)
	projection.warnings = append(projection.warnings, hostnameWarnings...)

	if hostnames != nil {
		blocker := fmt.Errorf("validating topology projection: %w", hostnames)
		projection.blockers = append(projection.blockers, blocker)

		if short {
			projection.shortHostnames = blocker
		}
	}

	if err := types.ValidateConfigSpec(*config); err != nil {
		projection.schema = fmt.Errorf("validating topology projection: %w", err)
	}

	return projection, nil
}

// checkInterfaceVLANs refuses a topology spec in which an interface of a node
// phenix starts has no VLAN: none at all, or an empty one. The phenix topology
// schema requires only the vlan key, so phenix stores such a topology, but
// minimega refuses the interface when the experiment starts ("VLAN must be
// non-empty string"). A VLAN that names no network of the document is kept:
// phenix allocates VLANs by name. External nodes are not started, and need
// none. The error names each device and interface to fix: an interface by
// its position when it has no name, or shares it with another. It also
// reports whether one of those interfaces has no vlan key or a null one,
// which phenix's schema refuses as well, rather than a blank VLAN, which it
// accepts.
func checkInterfaceVLANs(spec map[string]any) (*InterfaceVLANError, bool) {
	nodes, _ := spec[keyNodes].([]any)

	var (
		problems []string
		absent   bool
	)

	for _, entry := range nodes {
		node, ok := entry.(map[string]any)
		if !ok || node["external"] != nil {
			continue
		}

		hostname := specString(node, "general", "hostname")
		ifaces := specNodeInterfaces(node)
		labels := interfaceLabels(ifaces)

		for index, iface := range ifaces {
			named, missing := specInterfaceVLAN(iface)
			if named {
				continue
			}

			absent = absent || missing

			problems = append(problems, fmt.Sprintf(
				"interface %s of device %q has no VLAN: connect it to a network, or type a VLAN for it",
				labels[index], hostname,
			))
		}
	}

	if len(problems) == 0 {
		return nil, false
	}

	return &InterfaceVLANError{Problems: problems}, absent
}

// checkHostnames refuses a topology spec with a hostname phenix refuses (see
// [checkHostname]). The error names each hostname and why, in phenix's words.
// It also reports whether one of them is a single character, and returns the
// warnings phenix logs then about the hostnames it accepts. External nodes are
// not started, and phenix checks none of their hostnames.
func checkHostnames(spec map[string]any) (*NodeHostnameError, bool, []string) {
	var (
		problems, warnings []string
		short              bool
	)

	startedNodes(spec, func(hostname, osType string) {
		warning, err := checkHostname(hostname, osType)
		if err != nil {
			problems = append(problems, err.Error())
			short = short || isShortHostname(hostname)
		}

		if warning != "" {
			warnings = append(warnings, warning)
		}
	})

	if len(problems) == 0 {
		return nil, false, warnings
	}

	return &NodeHostnameError{Problems: problems}, short, warnings
}

// checkHostname reports what phenix makes of the hostname of a node it
// starts, whose os_type is osType: an error for a hostname phenix refuses, a
// single character, which phenix's schema refuses, or one phenix stores but
// refuses when it creates an experiment from the node (see
// [v1.CheckHostname]): "all", all digits, or "phenix" on a Windows node. It
// returns the warning phenix logs about a hostname it accepts.
func checkHostname(hostname, osType string) (string, error) {
	if isShortHostname(hostname) {
		return "", fmt.Errorf(
			"hostname '%s' is 1 character long: phenix requires hostnames of at least 2 characters, "+
				"as VyOS, Vyatta and Windows do",
			hostname,
		)
	}

	return v1.CheckHostname(hostname, osType)
}

// isShortHostname reports whether hostname is a single character, as
// phenix's schema counts characters.
func isShortHostname(hostname string) bool {
	return utf8.RuneCountInString(hostname) == 1
}

// startedNodes calls visit with the hostname and os_type of each node of a
// topology spec that phenix starts: every node but the external ones.
func startedNodes(spec map[string]any, visit func(hostname, osType string)) {
	nodes, _ := spec[keyNodes].([]any)

	for _, entry := range nodes {
		node, ok := entry.(map[string]any)
		if !ok || node["external"] != nil {
			continue
		}

		visit(specString(node, "general", "hostname"), specString(node, "hardware", "os_type"))
	}
}

// interfaceLabels names each interface of a node spec in a message: by its
// quoted name, or by its position when it has none or shares it with another
// (#2, "eth0" (#3)).
func interfaceLabels(ifaces []any) []string {
	names := make(map[string]int, len(ifaces))

	for _, iface := range ifaces {
		names[interfaceName(iface)]++
	}

	labels := make([]string, len(ifaces))

	for index, iface := range ifaces {
		name := interfaceName(iface)

		switch {
		case strings.TrimSpace(name) == "":
			labels[index] = fmt.Sprintf("#%d", index+1)
		case names[name] > 1:
			labels[index] = fmt.Sprintf("%q (#%d)", name, index+1)
		default:
			labels[index] = strconv.Quote(name)
		}
	}

	return labels
}

// addressUsers are the interfaces that use one IP or MAC address, in document
// order.
type addressUsers struct {
	// address names the address in a message: "IP address 10.0.0.5".
	address string
	// users names each interface: `interface "eth0" of device "web"`.
	users []string
	// own counts the interfaces of devices that are not included.
	own int
}

// checkInterfaceAddresses refuses a document in which two interfaces use the
// same IP address or the same MAC address: phenix stores such a topology, but
// the addresses clash once the experiment runs. Every device counts, including
// an external device's IP addresses and the devices of included topologies,
// which phenix merges into the experiment; an address only included devices
// use is their topology's to fix. An external device's MAC addresses do not
// count: phenix does not start it, and its schema has no MAC. IP addresses are
// compared parsed (see [interfaceIP]), and MAC addresses in any case and with
// any separators (see [interfaceMAC]). The error names each address and the
// interfaces that use it, in document order.
func (d *Document) checkInterfaceAddresses() error {
	var (
		shared []*addressUsers
		byKey  = map[string]*addressUsers{}
	)

	use := func(key, address, user string, included bool) {
		entry := byKey[key]
		if entry == nil {
			entry = &addressUsers{address: address, users: nil, own: 0}
			byKey[key] = entry
			shared = append(shared, entry)
		}

		entry.users = append(entry.users, user)

		if !included {
			entry.own++
		}
	}

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind != NodeKindDevice || node.Device == nil {
			continue
		}

		spec, err := normalizeSpecMap(node.Device.Spec)
		if err != nil {
			continue // ToTopology refuses it first
		}

		ifaces := specNodeInterfaces(spec)
		labels := interfaceLabels(ifaces)
		included := node.Device.IncludedFrom != ""
		external := spec["external"] != nil

		for index, entry := range ifaces {
			iface, ok := entry.(map[string]any)
			if !ok {
				continue
			}

			user := fmt.Sprintf("interface %s of device %q", labels[index], node.Device.Hostname)

			if addr, ok := interfaceIP(iface); ok {
				use("ip "+addr.String(), "IP address "+addr.String(), user, included)
			}

			if mac, ok := interfaceMAC(iface); ok && !external {
				use("mac "+mac.String(), "MAC address "+mac.String(), user, included)
			}
		}
	}

	var problems []string

	for _, entry := range shared {
		if len(entry.users) < 2 || entry.own == 0 {
			continue
		}

		first, second, more := entry.users[0], entry.users[1], len(entry.users[2:])
		users := first + " and " + second

		switch {
		case more == 1:
			users = first + ", " + second + " and 1 more interface"
		case more > 1:
			users = fmt.Sprintf("%s, %s and %d more interfaces", first, second, more)
		}

		problems = append(problems, fmt.Sprintf("%s is used by %s", entry.address, users))
	}

	if len(problems) == 0 {
		return nil
	}

	return &InterfaceAddressError{Problems: problems}
}

// interfaceIP reads the IP address a spec interface entry uses, as Go parses
// it, without a zone, and with an IPv4 address mapped into IPv6 as the IPv4
// address. A prefix length typed after it is ignored. It reports none for an
// interface that asks DHCP for its address, for one phenix brings up with no
// address (proto manual), and for an address that is blank or does not parse,
// which is the schema's to report.
//
// A manual interface's address is left out although the vrouter app's Vyatta
// and VyOS configuration assigns it: phenix's schema describes manual as no
// address, its Linux and Windows startup scripts and minirouter assign none,
// and the Builder's Inspector does not show it. An interface with qinq set
// counts: minirouter, which the Builder's Router and Firewall templates use,
// assigns its address, and so does Vyatta.
func interfaceIP(iface map[string]any) (netip.Addr, bool) {
	proto, _ := iface["proto"].(string)

	switch strings.ToLower(trimASCIISpace(proto)) {
	case "dhcp", "manual":
		return netip.Addr{}, false
	}

	text, _ := iface["address"].(string)
	text, _, _ = strings.Cut(text, "/")

	addr, err := netip.ParseAddr(trimASCIISpace(text))
	if err != nil {
		return netip.Addr{}, false
	}

	return addr.WithZone("").Unmap(), true
}

// interfaceMAC reads the MAC address a spec interface entry uses, in any case
// and with any separators: aa:bb:cc:dd:ee:ff, AA-BB-CC-DD-EE-FF and
// aabb.ccdd.eeff are one address. It reports none for a blank MAC, for which
// minimega makes one, and for one that is not twelve hex digits, which is the
// schema's to report.
func interfaceMAC(iface map[string]any) (net.HardwareAddr, bool) {
	const length = 6 // bytes of a MAC address

	text, _ := iface["mac"].(string)

	mac, err := hex.DecodeString(strings.NewReplacer(":", "", "-", "", ".", "").Replace(trimASCIISpace(text)))
	if err != nil || len(mac) != length {
		return nil, false
	}

	return net.HardwareAddr(mac), true
}

// trimASCIISpace trims the ASCII whitespace around an address or a proto. The
// editor trims the same characters (trimASCIISpace in validate.js), so both
// read an address alike: [strings.TrimSpace] and JavaScript's trim each trim a
// character the other keeps (U+0085 and U+FEFF).
func trimASCIISpace(text string) string {
	return strings.Trim(text, " \t\n\v\f\r")
}

// specInterfaceVLAN reports whether a spec interface entry names a VLAN and, when
// it does not, whether its vlan is missing or null rather than blank. An entry
// of the wrong shape, or a VLAN that is not a string, is left to the schema.
func specInterfaceVLAN(iface any) (bool, bool) {
	asMap, ok := iface.(map[string]any)
	if !ok {
		return true, false
	}

	value := asMap["vlan"]
	if value == nil {
		return false, true
	}

	vlan, ok := value.(string)

	return !ok || strings.TrimSpace(vlan) != "", false
}

// SpecV1 decodes the mapped topology spec into the versioned phenix topology
// spec. Callers that only need the stored representation should use
// [Topology.Spec] directly, which preserves keys unknown to v1.
//
// It decodes weakly, as phenix does (see types.DecodeTopologyFromConfig): the
// schema allows a string for vcpus and memory, and one address for dns.
func (t *Topology) SpecV1() (*v1.TopologySpec, error) {
	var spec v1.TopologySpec

	if err := mapstructure.WeakDecode(t.Spec, &spec); err != nil {
		return nil, fmt.Errorf("decoding topology spec: %w", err)
	}

	return &spec, nil
}

// handleNetworks maps each connected interface handle onto its network.
func (d *Document) handleNetworks() map[string]*Network {
	switchNetworks := make(map[string]*Network)

	for i := range d.Nodes {
		node := &d.Nodes[i]
		if node.Kind == NodeKindSwitch && node.Switch != nil {
			switchNetworks[node.ID] = d.NetworkByID(node.Switch.NetworkID)
		}
	}

	handles := make(map[string]*Network)

	for i := range d.Edges {
		edge := &d.Edges[i]

		source := d.NodeByID(edge.SourceNodeID)
		target := d.NodeByID(edge.TargetNodeID)

		if source == nil || target == nil {
			continue
		}

		device, handle, switchNode, ok := edgeEndpoints(
			source, edge.SourceHandleID, target, edge.TargetHandleID,
		)
		if !ok || device == nil {
			continue
		}

		if network := switchNetworks[switchNode.ID]; network != nil {
			handles[handle] = network
		}
	}

	return handles
}

// deviceSpec produces the topology node spec of a device node.
func deviceSpec(node *Node, handleNetworks map[string]*Network) (map[string]any, []string, error) {
	spec, err := normalizeSpecMap(node.Device.Spec)
	if err != nil {
		return nil, nil, err
	}

	if spec == nil {
		spec = map[string]any{}
	}

	var warnings []string

	if existing := specString(spec, "general", "hostname"); existing != "" &&
		existing != node.Device.Hostname {
		warnings = append(warnings, fmt.Sprintf(
			"device %q carries a node spec with hostname %q; the device hostname wins",
			node.Device.Hostname, existing,
		))
	}

	if !specSetString(spec, node.Device.Hostname, "general", "hostname") {
		return nil, nil, fmt.Errorf("node spec key %q is not an object", "general")
	}

	ifaces := specNodeInterfaces(spec)

	for _, handle := range node.Device.Interfaces {
		network, ok := handleNetworks[handle.ID]
		if !ok || network == nil {
			continue
		}

		iface := findInterface(ifaces, handle.Name)
		if iface == nil {
			warnings = append(warnings, fmt.Sprintf(
				"device %q is connected to network %q through interface %q, "+
					"but the node spec has no such interface; the connection was dropped",
				node.Device.Hostname, network.Name, handle.Name,
			))

			continue
		}

		iface["vlan"] = network.Name
	}

	return spec, warnings, nil
}

// findInterface locates a spec interface by name, preferring an exact match and
// falling back to a case-insensitive one.
func findInterface(ifaces []any, name string) map[string]any {
	var fallback map[string]any

	for _, iface := range ifaces {
		asMap, ok := iface.(map[string]any)
		if !ok {
			continue
		}

		ifaceName, _ := asMap["name"].(string)

		if ifaceName == name {
			return asMap
		}

		if fallback == nil && foldKey(ifaceName) == foldKey(name) {
			fallback = asMap
		}
	}

	return fallback
}
