x-common: &common
  init: true
  network_mode: host
  restart: always
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

services:
  phenix:
    image: ghcr.io/sandialabs/sceptre-phenix/phenix:main 
    command:
      - phenix
      - ui
      - --hostname-suffixes=-minimega,-phenix
      - --logs.publish-to-ui=info
      - --minimega-console
    container_name: phenix
    privileged: true
    pid: host
    <<: *common
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /var/log/phenix:/var/log/phenix
      - /etc/phenix:/etc/phenix
      - /var/run/netns:/var/run/netns:shared
      - /phenix:/phenix:shared
      - ./tmp/minimega:/tmp/minimega
      - ./tmp/phenix:/tmp/phenix
    environment:
      MM_FILEPATH: /phenix/images
    depends_on:
      - minimega
    healthcheck:
      test: phenix version
  minimega:
    image: ghcr.io/sandia-minimega/minimega:master
    container_name: minimega
    privileged: true
    cap_add:
      - ALL
    tty: true
    <<: *common
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/phenix:/var/log/phenix
      - /var/run/netns:/var/run/netns:shared
      - /phenix:/phenix:shared
      - ./tmp/minimega:/tmp/minimega
      - ./tmp/phenix:/tmp/phenix
    healthcheck:
      test: minimega -e version
    environment:
      MM_BASE: /tmp/minimega
      MM_FILEPATH: /phenix/images
      MM_PORT: 9000
      MM_DEGREE: 0  # number of nodes, 0 for single-node
      MM_CONTEXT: ${CONTEXT:-phenix}
      MM_LOGLEVEL: info
      MM_LOGFILE: /var/log/phenix/minimega.log
