//go:generate go run known_policy_gen.go
//go:build ignore

// This program generates known_policy.go. It can be invoked by running `go generate`
package main

import (
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

type Permission struct {
	Resource string
	Verb     string
}

var code = `// Code generated by go generate; DO NOT EDIT.
// This file was generated at build time.
// This contains all known role checks used in codebase.

package rbac

type Permission struct {
	Resource string
	Verb     string
}

var Permissions = []Permission{
{{- range .Permissions }}
	{"{{.Resource}}", "{{.Verb}}"},
{{- end }}
}
`
var packageTemplate = template.Must(template.New("").Parse(code))

func main() {
	var permissions []Permission
	re := regexp.MustCompile(`role\.Allowed\("([^"]+)", "([^"]+)"`)

	err := filepath.Walk("../..", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(info.Name(), ".go") && !strings.HasSuffix(info.Name(), "_test.go") {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			matches := re.FindAllStringSubmatch(string(content), -1)
			for _, match := range matches {
				pair := Permission{match[1], match[2]}
				found := false
				for _, p := range permissions {
					if p == pair {
						found = true
						break
					}
				}
				if !found {
					permissions = append(permissions, pair)
				}
			}
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	// sort checks alphabetically
	sort.SliceStable(permissions, func(i, j int) bool {
		if permissions[i].Resource == permissions[j].Resource {
			return permissions[i].Verb < permissions[j].Verb
		}

		return permissions[i].Resource < permissions[j].Resource
	})

	f, err := os.Create("known_policy.go")
	if err != nil {
		log.Fatal(err)
	}

	defer f.Close()

	packageTemplate.Execute(f, struct {
		Permissions []Permission
	}{
		Permissions: permissions,
	})
}
