apiVersion: v1
kind: Pod
metadata:
  name: headnode
spec:
  hostNetwork: true
  containers:
    - name: phenix
      image: phenix
      args:
        - phenix
        - ui
        - --hostname-suffixes=-minimega,-phenix
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: host-proc
          mountPath: /proc
        - name: host-tmp-minimega
          mountPath: /tmp/minimega
        - name: host-tmp-phenix
          mountPath: /tmp/phenix
        - name: host-log-phenix
          mountPath: /var/log/phenix
        - name: host-etc-phenix
          mountPath: /etc/phenix
        - name: host-phenix
          mountPath: /phenix
          mountPropagation: Bidirectional
    - name: minimega
      image: ghcr.io/sandia-minimega/minimega:latest
      env:
        - name: MM_FILEPATH
          value: /phenix/images
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: host-modules
          mountPath: /lib/modules
          readOnly: true
        - name: host-tmp-minimega
          mountPath: /tmp/minimega
        - name: host-tmp-phenix
          mountPath: /tmp/phenix
        - name: host-phenix
          mountPath: /phenix
          mountPropagation: Bidirectional
  volumes:
    - name: host-dev
      hostPath:
        path: /dev
    - name: host-proc
      hostPath:
        path: /proc
    - name: host-modules
      hostPath:
        path: /lib/modules
    - name: host-tmp-minimega
      hostPath:
        path: /tmp/minimega
        type: DirectoryOrCreate
    - name: host-tmp-phenix
      hostPath:
        path: /tmp/phenix
        type: DirectoryOrCreate
    - name: host-log-phenix
      hostPath:
        path: /var/log/phenix
        type: DirectoryOrCreate
    - name: host-etc-phenix
      hostPath:
        path: /etc/phenix
        type: DirectoryOrCreate
    - name: host-phenix
      hostPath:
        path: /phenix
        type: DirectoryOrCreate
