name: Examples

on:
  push:
    branches: ['**']
    paths:
      - 'examples/**'
      - '.github/workflows/examples.yml'
  pull_request:
    paths:
      - 'examples/**'
      - '.github/workflows/examples.yml'
  repository_dispatch:
    types: [apps-update]

env:
  GO_VERSION: '1.24'
  PYTHON_VERSION: '3.12'

jobs:
  check-go-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ env.GO_VERSION }}'
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Run Go Example Check
        run: make example-go

  check-python-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make -C examples install-dev
      - name: Run Python Example Check
        run: make example-python