name: Publish minimega Docker image
on:
  push:
    branches: ['**']
env:
  MM_REV: e8ce6d1
jobs:
  push-to-ghcr:
    name: Push minimega Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get short SHA
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/minimega
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=${{ env.MM_REV }}
      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: docker/Dockerfile.minimega
          build-args: |
            MM_REV=${{ env.MM_REV }}
            PHENIX_REVISION=${{ env.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
