name: Publish minimega Docker image
on:
  push:
    branches: [main]
jobs:
  push-to-ghcr:
    name: Push minimega Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get short SHA
        id: short
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.minimega
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/minimega:${{ steps.short.outputs.sha }}
            ghcr.io/${{ github.repository }}/minimega:${{ steps.short.outputs.branch }}
